version: "2"

linters:
  default: none
  enable:
    - staticcheck
    - govet
    - errcheck
    - ineffassign
    - unused
    - revive
    - gosec
    - gocritic
    - misspell

  settings:
    errcheck:
      check-type-assertions: true
      check-blank: true
    revive:
      rules:
        - name: blank-imports
        - name: context-as-argument
        - name: error-return
        - name: error-strings
        - name: receiver-naming

  exclusions:
    generated: lax
    paths:
      - webgui/node_modules/.*

formatters:
  enable:
    - gofmt
    - goimports
